url: 'https://strandberg.dev'
title: 'Aron Strandberg - Cloud Backend Engineer'
tagline: 'Stockholm, Sweden'
description: 'Cloud Backend Engineer based in Stockholm, specializing in GCP, Python and C#.'
author: 'Aron Strandberg'
locale: 'en_US'
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
