export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        performance: 'readonly',
        console: 'readonly',
        Map: 'readonly',
        Promise: 'readonly',
        Float32Array: 'readonly',
        Math: 'readonly',
        parseInt: 'readonly',
        requestAnimationFrame: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        JSON: 'readonly',
        Infinity: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        atob: 'readonly',
        google: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { vars: 'all', args: 'after-used', ignoreRestSiblings: false }],
      'no-undef': 'error',
      'no-unreachable': 'error',
      eqeqeq: ['error', 'always'],
      curly: 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-duplicate-imports': 'error',
      'no-self-compare': 'error',
    },
  },
];
